name: Deploy appimage ðŸ“¦

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  build-appimage:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pkg-resources coinor-libipopt-dev python3-pyqt5 python3-pyqt5.qtwebengine python3-pyqt5.qtmultimedia python3-qtpy libassimp-dev libqt5multimedia5-plugins swig

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install appimage-builder
        run: |
          sudo apt install -y patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool
          sudo pip install git+https://github.com/AppImageCrafters/appimage-builder.git

      - name: Build AppImage
        run: |
          appimage-builder --skip-test

      - name: move AppImage
        run: |
          mkdir AppImage
          mv ./*.AppImage* ./AppImage

      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: 'AppImage'

  deploy_appimage:
    name: ðŸ“¦ Deploy the appimage
    runs-on: ubuntu-20.04
    needs: [build-appimage]
    if: startsWith(github.ref, 'refs/tags')
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: AppImage
          path: AppImage

      - name: Publish appimage to release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: AppImage/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
